"use client";

import { useEffect, useState } from "react";
import { Sparkles, CheckCircle2, AlertTriangle, ClipboardList } from "lucide-react";
import { getPoppyReport, type PoppyReportResult } from "@/modules/poppy/actions";
import { ApplicantInterviewQuestions } from "@/components/dashboard/applicant-interview-questions";

/**
 * Poppy on the applicant panel. If a workflow-generated screening report exists,
 * show the full report (summary / strengths / concerns / recommendation +
 * questions). Otherwise fall back to the on-demand interview-question generator
 * (v0.1) — so there's only ever one Poppy section and no double generation.
 */
export function ApplicantPoppyReport({ applicationId }: { applicationId: string }) {
  const [res, setRes] = useState<PoppyReportResult | null>(null);

  useEffect(() => {
    let alive = true;
    setRes(null);
    getPoppyReport(applicationId).then((r) => {
      if (alive) setRes(r);
    });
    return () => {
      alive = false;
    };
  }, [applicationId]);

  // Still loading the report check — render nothing yet (avoids flashing the
  // fallback then swapping).
  if (res === null) return null;

  // No workflow report → fall back to the on-demand v0.1 generator.
  if (res.status !== "ready" || !res.report) {
    return <ApplicantInterviewQuestions applicationId={applicationId} />;
  }

  const r = res.report;
  return (
    <div>
      <p className="flex items-center gap-1.5 text-xs uppercase tracking-wide text-gray-400">
        <Sparkles className="h-3.5 w-3.5 text-brand-500" /> Poppy · Screening report
      </p>

      {r.summary && <p className="mt-1.5 text-sm text-gray-800">{r.summary}</p>}

      {r.recommendation && (
        <p className="mt-2 inline-flex items-start gap-1.5 rounded-lg bg-brand-50 px-2.5 py-1.5 text-sm font-medium text-brand-800">
          <ClipboardList className="mt-0.5 h-4 w-4 shrink-0" /> {r.recommendation}
        </p>
      )}

      <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2">
        {r.strengths.length > 0 && (
          <div className="rounded-xl border border-white/50 bg-white/60 p-3 backdrop-blur-sm">
            <p className="flex items-center gap-1.5 text-xs font-semibold text-green-700">
              <CheckCircle2 className="h-3.5 w-3.5" /> Strengths
            </p>
            <ul className="mt-1 list-disc space-y-1 pl-4 text-sm text-gray-700">
              {r.strengths.map((s, i) => <li key={i}>{s}</li>)}
            </ul>
          </div>
        )}
        {r.concerns.length > 0 && (
          <div className="rounded-xl border border-white/50 bg-white/60 p-3 backdrop-blur-sm">
            <p className="flex items-center gap-1.5 text-xs font-semibold text-amber-700">
              <AlertTriangle className="h-3.5 w-3.5" /> Worth checking
            </p>
            <ul className="mt-1 list-disc space-y-1 pl-4 text-sm text-gray-700">
              {r.concerns.map((c, i) => <li key={i}>{c}</li>)}
            </ul>
          </div>
        )}
      </div>

      {r.questions.length > 0 && (
        <div className="mt-3 space-y-3">
          <p className="text-xs font-semibold text-gray-500">Suggested interview questions</p>
          {r.questions.map((g, gi) => (
            <div key={gi} className="rounded-xl border border-white/50 bg-white/60 p-3 backdrop-blur-sm">
              <p className="text-xs font-semibold text-brand-700">{g.category}</p>
              <ul className="mt-1.5 space-y-2">
                {g.questions.map((q, qi) => (
                  <li key={qi} className="text-sm">
                    <p className="text-gray-900">{q.question}</p>
                    {q.rationale && <p className="mt-0.5 text-xs text-gray-500">{q.rationale}</p>}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}

      {res.generatedAt && (
        <p className="mt-2 text-[11px] text-gray-400">
          Generated by Poppy {new Date(res.generatedAt).toLocaleDateString("en-GB", { day: "numeric", month: "short" })}. Review before use.
        </p>
      )}
    </div>
  );
}
