"use client";

import { useEffect, useState } from "react";
import { Sparkles, RefreshCw, AlertTriangle } from "lucide-react";
import {
  getInterviewQuestions,
  regenerateInterviewQuestions,
  type InterviewQuestionsResult,
} from "@/modules/ruby/actions";

/**
 * Ruby — AI interview questions for an applicant. Compares the application + CV
 * against the job description. Renders nothing unless the company has Ruby.
 * Auto-generates the first time it's opened (if a CV is present).
 */
export function ApplicantInterviewQuestions({ applicationId }: { applicationId: string }) {
  const [res, setRes] = useState<InterviewQuestionsResult | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    let alive = true;
    setRes(null);
    getInterviewQuestions(applicationId).then((r) => {
      if (alive) setRes(r);
    });
    return () => {
      alive = false;
    };
  }, [applicationId]);

  async function regenerate() {
    setBusy(true);
    const r = await regenerateInterviewQuestions(applicationId);
    setBusy(false);
    setRes(r);
  }

  // Not entitled → show nothing at all.
  if (res && !res.entitled) return null;

  const Header = (
    <div className="flex items-center justify-between">
      <p className="flex items-center gap-1.5 text-xs uppercase tracking-wide text-gray-400">
        <Sparkles className="h-3.5 w-3.5 text-brand-500" /> Ruby · Interview questions
      </p>
      {res?.status === "ready" && (
        <button
          onClick={regenerate}
          disabled={busy}
          className="inline-flex items-center gap-1 rounded-lg border border-white/40 bg-white/60 px-2 py-1 text-xs font-medium text-gray-700 hover:bg-white/60 disabled:opacity-60"
        >
          <RefreshCw className={`h-3 w-3 ${busy ? "animate-spin" : ""}`} /> {busy ? "Working…" : "Regenerate"}
        </button>
      )}
    </div>
  );

  // Loading / generating (first open auto-generates — can take a few seconds).
  if (res === null || busy) {
    return (
      <div>
        {Header}
        <p className="mt-1 flex items-center gap-2 text-sm text-gray-500">
          <Sparkles className="h-4 w-4 animate-pulse text-brand-500" />
          Ruby is reading the application and CV…
        </p>
      </div>
    );
  }

  if (res.status === "needs_input") {
    return (
      <div>
        {Header}
        <p className="mt-1 text-sm text-gray-500">
          Ruby will draft interview questions once the applicant has submitted their application form (and any workflow forms). A CV adds extra detail but isn&apos;t required.
        </p>
      </div>
    );
  }

  if (res.status === "error") {
    return (
      <div>
        {Header}
        <p className="mt-1 flex items-start gap-2 text-sm text-red-600">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
          {res.error ?? "Ruby couldn't generate questions."}
        </p>
        <button
          onClick={regenerate}
          disabled={busy}
          className="mt-2 inline-flex items-center gap-1 rounded-lg border border-white/40 bg-white/60 px-2.5 py-1 text-xs font-medium text-gray-700 hover:bg-white/60 disabled:opacity-60"
        >
          <RefreshCw className="h-3 w-3" /> Try again
        </button>
      </div>
    );
  }

  const groups = res.groups ?? [];

  return (
    <div>
      {Header}
      {groups.length === 0 ? (
        <p className="mt-1 text-sm text-gray-500">Ruby didn&apos;t find anything notable to ask about.</p>
      ) : (
        <div className="mt-2 space-y-3">
          {groups.map((g, gi) => (
            <div key={gi} className="rounded-xl border border-white/50 bg-white/60 p-3 backdrop-blur-sm">
              <p className="text-xs font-semibold text-brand-700">{g.category}</p>
              <ul className="mt-1.5 space-y-2">
                {g.questions.map((q, qi) => (
                  <li key={qi} className="text-sm">
                    <p className="text-gray-900">{q.question}</p>
                    {q.rationale && <p className="mt-0.5 text-xs text-gray-500">{q.rationale}</p>}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}
      {res.generatedAt && (
        <p className="mt-2 text-[11px] text-gray-400">
          Generated by Ruby {new Date(res.generatedAt).toLocaleDateString("en-GB", { day: "numeric", month: "short" })}. Review before use.
        </p>
      )}
    </div>
  );
}
